### ISSUE TITLE
file selection

### ISSUE THREAD

**Issue by CPernet** [martynmcfarquhar/MRM#1]
Hi Martyn,

been playing with the toolbox and it works nicely - one issue is that people don't reorganize the beta/contrast images which makes selection a right pain in the back side

consider this simple change in MRM_selectDataNew
line 151 onward

clear files;
try 
   out = spm_select(Inf,'.nii','select images');
    for i=1:size(out,1); files{i}=out(i,:); end
catch
   files = uigetfile_n_dir();
end

if people have spm in the path (they shoud) it calls spm_select which allows to use the editor rather then clicking and therefore paste huge number of files at one go :-)

**Comment by martynmcfarquhar** [comment]
Hi Cyril,

Glad you've managed to get the toolbox working as it should. Thank you very much for the suggestion. I am aware that file selection is a bit of a pain at the moment, and that's a very nice solution! I especially like the fact it can fall back on the included file selector if needs be.

I shall include the changes in the next release. Thanks again!

**Comment by CPernet** [comment]
because it's nifti, you can have 4D files, and nii,1 nii,2 etc could be used with spm_select also change

% Check that all files were .nii
for i = 1:size(files,2)
    [~, ~, ext] = fileparts(files{i});

```
if strncmp(ext, '.nii',3) == 0
    msgbox('At least one file does not appear to be NIfTI.', ...
           'File error');

    return 
end
```

end

--> strncmp
